### ISSUE TITLE
Attempting to send a print to a nonexistant default printer segfaults the server

### ISSUE THREAD

**Issue by ckiee** [michaelrsweet/hp-printer-app#14]
**Describe the bug**
Attempting to send a print to a nonexistant default printer segfaults the server.

**To Reproduce**
1. Run the server as root
2. Set it up with `hp_deskjet`
3. Submit a print with the `submit` CLI without a `-d` argument
4. Watch the server process segfault.

**Expected behavior**
I expected it to work the same as when I do specify a `-d` in the submit command (still no print, but it gets further along and thinks it printed fine)

**Screenshots**
Coredump report here: https://i.ckie.dev/ms6hchb.txt

**System Information:**
- `Linux pansear 5.10.99 #1-NixOS SMP Tue Feb 8 17:30:41 UTC 2022 x86_64 GNU/Linux`
- HP Deskjet 2510
- `SNAP_COMMON=/run` so it can `bind` the socket.

**Comment by michaelrsweet** [comment]
@ckiee I believe this is fixed now, please test once the new snap is posted...

**Comment by ckiee** [comment]
Sorry I missed the last email! (And thanks for fixing it, though I haven't tried it yet)
