### ISSUE TITLE
Unable to print

### ISSUE THREAD

**Issue by ChemicalXandco** [michaelrsweet/hp-printer-app#17]
Installed 1.2 on arch linux. Trying to add the printer at localhost:8000 frequently results in 'Invalid form submission.' being displayed at the top of the screen but given enough tries it is possible to add it. When it is added printer shows up as 'HP DeskJet series' but not is full name 'HP Officejet Pro 7740 Series' as it does on the official driver. Printer has 2 trays but in the media section there is only an option for tray 1. Trying to change any option more likely than not fails with 'Invalid form submission.'. Attempting to print from for example libreoffice either errors out after a minute or immediately freezes and crashes.

full log:
```
E [2022-06-15T18:18:13.604Z] Unable to create listener socket for '/usr/var/run/hp-printer-app.sock': No such file or directory
W [2022-06-15T18:22:09.539Z] [Printer abc] Driver does not support identification.
W [2022-06-15T18:22:09.539Z] [Printer abc] Driver does not support a self-test page.
E [2022-06-15T18:22:09.635Z] [Client 11] Unable to encrypt connection: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
W [2022-06-15T18:40:19.970Z] [Printer hp] Driver does not support identification.
W [2022-06-15T18:40:19.970Z] [Printer hp] Driver does not support a self-test page.
E [2022-06-15T18:40:19.986Z] [Client 77] Unable to encrypt connection: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
E [2022-06-15T18:40:23.071Z] [Device] Unable to lookup \'HP40B03476451B.local:9100\': Name or service not known
W [2022-06-15T18:44:55.767Z] [Printer hpe] Driver does not support identification.
W [2022-06-15T18:44:55.767Z] [Printer hpe] Driver does not support a self-test page.
```

**Comment by michaelrsweet** [comment]
The log shows that the local self-signed certificate is bad. Delete any certificate files in /etc/cups/ssl and ~/.cups/ssl and then try printing again.

Please note that the HP Printer Application is NOT a full-functioned HP printer driver package like HPLIP - for that you want Till Kamppeter's [hplip-printer-app](https://github.com/OpenPrinting/hplip-printer-app) instead. The primary focus of this software is network PCL laser printers, with limited support for color inkjet printers provided by the (old) HP sample driver code from CUPS.
