### ISSUE TITLE
Ability to modify server options with snap

### ISSUE THREAD

**Issue by cptaffe** [michaelrsweet/hp-printer-app#21]
**Is your feature request related to a problem? Please describe.**

The article [_A New Way to Print in Linux_](https://openprinting.github.io/documentation/01-printer-application/) mentions Snaps several times, so I assume it's the preferred installation method.

When installing `hp-printer-app` via snap, the service runs [this file](https://github.com/michaelrsweet/hp-printer-app/blob/master/snap/local/hp-printer-app-server#L11) which contains hardcoded options. This results in being unable to solve simple issues such as: 
- Unable to access the server from another machine via DNS address, such as `http://printserver.home.arpa:8000`. I need to pass `-o listen-hostname=printserver.home.arpa`

```
[Client 1] Accepted connection from '10.0.2.163'.
[Client 1] HTTP_STATE_GET http://printserver.home.arpa:8000/ HTTP/1.1 (en-US,en;q=0.9)
[Client 1] Bad Host: header 'printserver.home.arpa'.
[Client 1] Bad Request
[Client 1] Closing connection from '10.0.2.163'.
```

- Accessing via IP results in self-signed certificate errors. I need to issue a cert via my own self-signed CA.

**Describe the solution you'd like**

I believe at least the first issue is fixable via configuration options, passed via `-o` (as documented [here](https://github.com/michaelrsweet/hp-printer-app/blob/master/DOCUMENTATION.md#running-a-server)), but since snaps are immutable I'm unable to edit the `hp-printer-app-server` file. I believe snap [configuration](https://snapcraft.io/docs/configuration-in-snaps) could provide a way to expose each `-o` as a config option, settable via `snap set hp-printer-app-server ...`.

**Comment by michaelrsweet** [comment]
Oh, I should note that PAPPL-based printer applications will try to defend against DNS rebinding attacks, so all client requests need to target the mDNS hostname ("hostname.local"), the system hostname (whatever "hostname" reports), an IP address, or (for loopback/domain socket access) "localhost". Right now there is no provision for a system that has multiple FQDNs beyond "hostname.local" and "hostname.domain"...

**Comment by michaelrsweet** [comment]
OK, so I have this implemented for LPrint and will carry that over to hp-printer-app as well...

**Comment by cptaffe** [comment]
I set the system hostname to be the domain I use on my local network, e.g. `printserver.home.arpa`, but I would like to be able to proxy to use a non-hostname domain and proxy to different printer app UIs + CUPS via nginx. The connection would be via `localhost`, but the `Host` header would report the original domain, e.g. `printer-apps.home.arpa` -- would that fail for PAPPL-based applications?

**Comment by michaelrsweet** [comment]
Right now PAPPL isn't setup to support multiple domain names. It is intended only to support local direct printing with future support for the IPP "Shared Infrastructure" (cloud) extensions to allow remote network access vs. trying to use brittle (and insecure) HTTP/SSH proxy solutions and exposing a local server to a WAN/the Internet.

**Comment by michaelrsweet** [comment]
[master 7f8980f] Update snap to support configuration and PAPPL 1.3.1 (Issue #21)

**Comment by cptaffe** [comment]
> trying to use brittle (and insecure) HTTP/SSH proxy solutions and exposing a local server to a WAN/the Internet.

In this case I would be exposing the interface to my local network only, using Nginx allows handling certs / routing multiple FQDNs for convenient name-based access to several print apps / CUPS running on the same VM.

**Comment by cptaffe** [comment]
@michaelrsweet when will 1.2.1 be available with these changes? The version available to me doesn't have these changes yet.

```
; snap info hp-printer-app
name:      hp-printer-app
summary:   HP Printer Application
publisher: Michael Sweet (michaelrsweet)
store-url: https://snapcraft.io/hp-printer-app
license:   unset
description: |
  HP Printer Application is sample printer application for Hewlett Packard PCL
  (and compatible) printers.  It is based on PAPPL (Printer Application
  Framework), a simple C-based framework/library for developing CUPS Printer
  Applications, which are the recommended replacement for printer drivers.
commands:
  - hp-printer-app
services:
  hp-printer-app.hp-printer-app-server: simple, enabled, active
snap-id:      TsR8cclxOUKWUcf96gkX5B0XjlB2kr5J
tracking:     latest/stable
refresh-date: today at 13:54 EDT
channels:
  latest/stable:    1.2.0 2022-11-03 (386) 2MB -
  latest/candidate: 1.2.0 2022-11-03 (386) 2MB -
  latest/beta:      1.2.0 2022-11-03 (386) 2MB -
  latest/edge:      1.2.0 2022-11-03 (386) 2MB -
installed:          1.2.0            (386) 2MB -
```
