### ISSUE TITLE
Installation issue using makefile

### ISSUE THREAD

**Issue by dipanshu231099** [michaelrsweet/hp-printer-app#3]
**Describe the bug**
I have been trying to install hp-printer-app using the makefile. Also I have installed the most recent version of pappl on ubuntu (using the makefile). The installation of pappl seems to be correct as I was able to test it using testpappl and the web-interface is running just fine. 
I am running Ubuntu-20.04 and have installed libjpeg9-dev (there is a specific reason I am mentioining this fact)

**To Reproduce**
1. Run `make`
2. throws the error `make: *** [Makefile:55: hp-printer-app] Error 1` with the very first line showing `Package 'pappl' requires 'libjpeg >= 9.0' but version of libjpeg is 2.0.3` however since pappl is using libjpeg.h and I have libjpeg9-dev installed I do not get why I am recieving this err.
EDIT
It also shows multiple errors of this type `/usr/bin/ld: /home/dipanshu/hp-printer-app/hp-printer-app.c:430: undefined reference to 'papplDeviceWrite' `. So is there some problem with pappl installation ?

**System Information:**
 - OS: Ubuntu 20.04
 - Browser chrome

**Comment by michaelrsweet** [comment]
@dipanshu231099 It would be useful for your to do:

    make clean all 2>&1 | tee make.log

and then attach the make.log file to this issue.

**Comment by dipanshu231099** [comment]
Problem has been solved. I built libjpeg9 from source and then created a symbolic link for libpam.so.0. That has built the application for me.
