### ISSUE TITLE
hp-printer-app does not start at all, no error

### ISSUE THREAD

**Issue by tillkamppeter** [michaelrsweet/hp-printer-app#6]
**Describe the bug**
I have built the Snap of the current GIT snapshot of the `hp-printer-app` with
```
snapcraft clean
snapcraft snap
```
Then I have installed the Snap via
```
sudo snap install --dangerous hp-printer-app_1.0_amd64.snap
```
and started it with
```
hp-printer-app -o log-level=debug server
```
Instead of starting the server mode it immediately exited, without any error message or debug log message. Exit status is 1.

**To Reproduce**
Do the commands mentioned above.

**Expected behavior**
`hp-printer-app` running in server mode so that one can add printers and print.

**System Information:**
 - Ubuntu 20.04 Focal Fossa
 - Note: Snap building does not work on Ubuntu 20.10 Groovy Gorilla

**Comment by michaelrsweet** [comment]
@tillkamppeter FWIW, the hp-printer-app snap is being built automatically: <https://snapcraft.io/hp-printer-app/builds>

Make sure you build against the latest PAPPL and hp-printer-app code - I had to push several fixes to get the snap building properly...

**Comment by tillkamppeter** [comment]
I have always built with the most recent code from GitHub. Now I have done a `snapcraft clean` and a `snapcraft snap`.
Then I have started the application again, again with
```
hp-printer-app -o log-level=debug server
```
Now it does not immediately exit with code 1 and without error message, but, instead, it keeps running, but though I am running it in debug mode, it does not show any message, so seems to hang before setting up logging. It also does not start listening. I can neither access the web interface with a browser nor can does the system show as `_ipps_system._tcp` in `avahi-discover` or `avahi-browse`.
If I run a non-server task, here
```
hp-printer-app -o log-level=debug drivers
```
I get only the message
```
hp-printer-app: No system callback specified.
```
I get absolutely the same results if I do not build by myself but, instead, download from the Snap Store:
```
sudo snap install --edge hp-printer-app
```
I have also tried to install my self-built Snap with
```
sudo snap install --devmode hp-printer-app_1.0_amd64.snap
```
and get the same results, so it seems that it is not a problem of confinement.

**Comment by tillkamppeter** [comment]
Concerning the output
```
hp-printer-app: No system callback specified.
```
when using the `drivers` sub-command, `ps-printer-app` has a system callback and lists the drivers. So something with your support for a PAPPL-built-in default system callback seems to be wrong.

**Comment by tillkamppeter** [comment]
I have found now where the log is hidden
```
/tmp/snap.hp-printer-app/tmp/pappl427934.log
```
It contains
```
I [2020-10-28T08:03:56.717Z] Starting log, system up 0 second(s), listening for connections on 'till-x1yoga.local:0'.
D [2020-10-28T08:03:56.717Z] Adding 'image/jpeg' to 'image/pwg-raster' filter.
D [2020-10-28T08:03:56.717Z] Adding 'image/png' to 'image/pwg-raster' filter.
I [2020-10-28T08:03:56.717Z] Listening for connections on '/tmp/hp-printer-app1000.sock'.
D [2020-10-28T08:03:56.717Z] Adding resource for '/favicon.png'.
D [2020-10-28T08:03:56.717Z] Adding resource for '/navicon.png'.
D [2020-10-28T08:03:56.717Z] Adding resource for '/style.css'.
D [2020-10-28T08:03:56.717Z] Adding resource for '/'.
D [2020-10-28T08:03:56.717Z] Adding resource for '/addprinter'.
D [2020-10-28T08:03:56.717Z] Adding resource for '/config'.
I [2020-10-28T08:03:56.717Z] Starting system.
I [2020-10-28T08:04:28.963Z] Shutting down system.
```
The last line was probably produced when I stopped the Printer Application with `killall hp-printer-app`.

**Comment by tillkamppeter** [comment]
I got it working now, see issue #7. So now it is actually running but not intuitive to run it correctly.
